"use client";
import { useState, useRef } from "react";
import FileDropZone from "../components/FileDropZone";

async function hashFile(file) {
  const buffer = await file.arrayBuffer();
  const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

function formatDate(date) {
  return date.toISOString().replace("T", " ").replace(/\.\d+Z/, " UTC");
}

export default function ProofPage() {
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const canvasRef = useRef(null);

  async function handleFile(file) {
    setLoading(true);
    try {
      const hash = await hashFile(file);
      const now = new Date();
      setResult({
        fileName: file.name,
        fileSize: (file.size / 1024).toFixed(1) + " KB",
        hash,
        timestamp: formatDate(now),
        timestampISO: now.toISOString(),
      });
    } finally {
      setLoading(false);
    }
  }

  function downloadCertificate() {
    if (!result) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");
    const W = 800, H = 560;
    canvas.width = W;
    canvas.height = H;

    // Background
    ctx.fillStyle = "#0a0a0f";
    ctx.fillRect(0, 0, W, H);

    // Border
    ctx.strokeStyle = "#e94560";
    ctx.lineWidth = 3;
    ctx.strokeRect(20, 20, W - 40, H - 40);

    // Inner border
    ctx.strokeStyle = "#2a2a3e";
    ctx.lineWidth = 1;
    ctx.strokeRect(30, 30, W - 60, H - 60);

    // Title
    ctx.fillStyle = "#e94560";
    ctx.font = "bold 28px system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("PROOF OF OWNERSHIP CERTIFICATE", W / 2, 80);

    // Subtitle
    ctx.fillStyle = "#a0a0b0";
    ctx.font = "14px system-ui, sans-serif";
    ctx.fillText("Generated by ArtShield — artshield.vercel.app", W / 2, 105);

    // Divider
    ctx.strokeStyle = "#2a2a3e";
    ctx.beginPath();
    ctx.moveTo(60, 125);
    ctx.lineTo(W - 60, 125);
    ctx.stroke();

    // Content
    ctx.textAlign = "left";
    ctx.fillStyle = "#a0a0b0";
    ctx.font = "14px system-ui, sans-serif";

    const lines = [
      { label: "File Name:", value: result.fileName },
      { label: "File Size:", value: result.fileSize },
      { label: "SHA-256 Hash:", value: "" },
      { label: "", value: result.hash },
      { label: "Timestamp:", value: result.timestamp },
    ];

    let y = 165;
    for (const line of lines) {
      if (line.label) {
        ctx.fillStyle = "#a0a0b0";
        ctx.font = "bold 14px system-ui, sans-serif";
        ctx.fillText(line.label, 60, y);
      }
      if (line.value) {
        ctx.fillStyle = "#f0f0f0";
        ctx.font = "14px monospace";
        const xOff = line.label ? 180 : 60;
        ctx.fillText(line.value, xOff, y);
      }
      y += 32;
    }

    // Explanation box
    y += 20;
    ctx.fillStyle = "#1a1a2e";
    ctx.fillRect(50, y, W - 100, 120);
    ctx.strokeStyle = "#2a2a3e";
    ctx.strokeRect(50, y, W - 100, 120);

    ctx.fillStyle = "#a0a0b0";
    ctx.font = "12px system-ui, sans-serif";
    ctx.textAlign = "center";
    const explanation = [
      "This SHA-256 hash is a unique digital fingerprint of your original file.",
      "If anyone claims your art as theirs, this certificate proves you had the",
      "exact file at this timestamp. The hash changes if even 1 pixel is altered.",
      "",
      "Keep this certificate and your original file in a safe place.",
      "Consider emailing it to yourself for a secondary timestamp.",
    ];
    let ey = y + 22;
    for (const line of explanation) {
      ctx.fillText(line, W / 2, ey);
      ey += 17;
    }

    // Download
    const link = document.createElement("a");
    link.download = `artshield_proof_${result.hash.slice(0, 12)}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  }

  function copyHash() {
    if (result) {
      navigator.clipboard.writeText(result.hash);
    }
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-2">proof of ownership</h1>
      <p className="text-[var(--muted)] mb-8">
        drop your art below and we&apos;ll generate a unique hash (digital fingerprint) for it. if anyone ever tries to claim your art, this proves you had the original file.
      </p>

      <FileDropZone onFile={handleFile} />

      {loading && (
        <div className="mt-8 text-center text-[var(--muted)]">Calculating hash...</div>
      )}

      {result && !loading && (
        <div className="mt-8 bg-[var(--card)] border border-[var(--border)] rounded-xl p-6">
          <h2 className="text-lg font-semibold mb-4 text-[var(--accent)]">Certificate Generated</h2>

          <div className="space-y-3 text-sm">
            <div>
              <span className="text-[var(--muted)]">File: </span>
              <span>{result.fileName}</span>
              <span className="text-[var(--muted)] ml-2">({result.fileSize})</span>
            </div>
            <div>
              <span className="text-[var(--muted)]">SHA-256: </span>
              <code className="text-xs bg-[var(--background)] px-2 py-1 rounded border border-[var(--border)] break-all">
                {result.hash}
              </code>
              <button
                onClick={copyHash}
                className="ml-2 text-xs text-[var(--accent)] hover:text-[var(--accent-hover)]"
              >
                Copy
              </button>
            </div>
            <div>
              <span className="text-[var(--muted)]">Timestamp: </span>
              <span>{result.timestamp}</span>
            </div>
          </div>

          <div className="mt-6 flex gap-3">
            <button
              onClick={downloadCertificate}
              className="px-4 py-2 bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white rounded-lg text-sm font-medium transition-colors"
            >
              Download Certificate (PNG)
            </button>
          </div>

          <p className="mt-4 text-xs text-[var(--muted)]">
            Tip: Email this certificate to yourself for an additional timestamp from your email provider.
          </p>
        </div>
      )}

      <canvas ref={canvasRef} className="hidden" />
    </div>
  );
}
